name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos_build:
    name: MacOS (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["macos-14"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          xcodebuild archive -archivePath dist -scheme Statusfy
      - run: cp dist/Statusfy.xcarchive/Products/Applications/Statusfy.app Statusfy.app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: Statusfy.app
          name: ${{ matrix.os }}-binaries
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ macos_build]
    name: Upload binaries to release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download binaries
        uses: actions/download-artifact@v4
        id: download
        with:
          path: binaries

      - name: List downloaded binaries
        run: ls -R binaries

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{steps.download.outputs.download-path}}/**/*"


